import { TextField } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Coin from '../server/models/Coin'

interface HomeProps{
  coins:Coin[]
}

const Home: NextPage<HomeProps> = ({coins}) => {



  return (
    <div >
      <Head>
        <title>Satrex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mainBanner ">
          <div className="bannerContent position-relative">
              <TextField label="Name" variant="standard" />
          </div>
      </main>

    </div>
  )
}



export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const coins = await Coin.getALlCoins()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      coins,
    },
  }
}

export default Home